version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx_broker
    restart: always
    ports:
      - "1883:1883"   # MQTT Port
      - "8083:8083"   # WebSocket Port
      - "8084:8084"   # Secure WebSocket Port
      - "18083:18083" # Dashboard Port
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=0.0.0.0
      - EMQX_ALLOW_ANONYMOUS=false  # Disables anonymous authentication
      - EMQX_AUTH__MONGODB__ENABLE=false  # Disable MongoDB authentication
      - EMQX_AUTH__USER__ENABLE=true  # Enable username/password authentication
    volumes:
      - ./emqx_auth.conf:/opt/emqx/etc/plugins/emqx_auth_mnesia.conf
