version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - ./emqx.conf:/etc/emqx/emqx.conf  # Mount EMQX config file 
      - ./passwords:/opt/emqx/data/passwords/passwords
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=0.0.0.0
      - EMQX_ALLOW_ANONYMOUS=false  # Disable anonymous access
    restart: always

networks:
   emqx-net:
     driver: bridge
