version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"   # MQTT Port
      - "8883:8883"   # MQTT over SSL
      - "8081:8081"   # API Port
      - "18083:18083" # Web Dashboard
    volumes:
      - ./emqx.conf:/opt/emqx/etc/emqx.conf
      - ./acl.conf:/opt/emqx/etc/acl.conf
    environment:
      EMQX_ALLOW_ANONYMOUS: "false"  # Disable anonymous access
      EMQX_AUTH__USERNAME__PASSWORD: "on"  # Enable username/password authentication
      EMQX_AUTH__USER__1__USERNAME: "mqttuser"
      EMQX_AUTH__USER__1__PASSWORD: "mqttpass"
